name: Update Deadside Server Status

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  update-server-status:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install GameDig
        run: npm install gamedig

      - name: Query Deadside server
        run: |
          node .github/workflows/query-server.js

          echo "========== FILES =========="
          ls -la

          echo "========== SERVER STATUS =========="
          cat server-status.json

      - name: Commit server status
        run: |
          echo "========== GIT STATUS =========="
          git status

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f server-status.json

          echo "========== AFTER GIT ADD =========="
          git status

          if git diff --cached --quiet; then
            echo "No server status changes to commit."
          else
            git commit -m "Update Deadside server status"
            git push
          fi