name: Deadside Server Status

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  query:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout website
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install GameDig
        run: npm install gamedig

      - name: Query Deadside
        run: node .github/workflows/query-server.js

      - name: Show result
        run: cat server-status.json