name: Deadside Server Status

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout website
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Query GS4U
        run: node .github/workflows/query-server.js

      - name: Show result
        run: cat server-status.json

      - name: Commit server status
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add server-status.json

          if git diff --cached --quiet; then
            echo "No status changes to commit."
          else
            git commit -m "Update Deadside server status"
            git push
          fi